/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as AppRouteImport } from "./routes/_app"
import { Route as AppIndexRouteImport } from "./routes/_app.index"
import { Route as AppBudgetRouteImport } from "./routes/_app.budget"
import { Route as AppExpensesRouteImport } from "./routes/_app.expenses"
import { Route as AppSettingsRouteImport } from "./routes/_app.settings"
import { Route as AppExpensesNewRouteImport } from "./routes/_app.expenses_.new"
import { Route as AppExpensesExpenseIdEditRouteImport } from "./routes/_app.expenses_.$expenseId.edit"

const AppRoute = AppRouteImport.update({
  id: "/_app",
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetRoute = AppBudgetRouteImport.update({
  id: "/budget",
  path: "/budget",
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: "/expenses",
  path: "/expenses",
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesNewRoute = AppExpensesNewRouteImport.update({
  id: "/expenses_/new",
  path: "/expenses/new",
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesExpenseIdEditRoute =
  AppExpensesExpenseIdEditRouteImport.update({
    id: "/expenses_/$expenseId/edit",
    path: "/expenses/$expenseId/edit",
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof AppIndexRoute
  "/budget": typeof AppBudgetRoute
  "/expenses": typeof AppExpensesRoute
  "/settings": typeof AppSettingsRoute
  "/expenses/new": typeof AppExpensesNewRoute
  "/expenses/$expenseId/edit": typeof AppExpensesExpenseIdEditRoute
}
export interface FileRoutesByTo {
  "/budget": typeof AppBudgetRoute
  "/expenses": typeof AppExpensesRoute
  "/settings": typeof AppSettingsRoute
  "/": typeof AppIndexRoute
  "/expenses/new": typeof AppExpensesNewRoute
  "/expenses/$expenseId/edit": typeof AppExpensesExpenseIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_app": typeof AppRouteWithChildren
  "/_app/budget": typeof AppBudgetRoute
  "/_app/expenses": typeof AppExpensesRoute
  "/_app/settings": typeof AppSettingsRoute
  "/_app/": typeof AppIndexRoute
  "/_app/expenses_/new": typeof AppExpensesNewRoute
  "/_app/expenses_/$expenseId/edit": typeof AppExpensesExpenseIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/budget"
    | "/expenses"
    | "/settings"
    | "/expenses/new"
    | "/expenses/$expenseId/edit"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/budget"
    | "/expenses"
    | "/settings"
    | "/"
    | "/expenses/new"
    | "/expenses/$expenseId/edit"
  id:
    | "__root__"
    | "/_app"
    | "/_app/budget"
    | "/_app/expenses"
    | "/_app/settings"
    | "/_app/"
    | "/_app/expenses_/new"
    | "/_app/expenses_/$expenseId/edit"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_app": {
      id: "/_app"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/": {
      id: "/_app/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/budget": {
      id: "/_app/budget"
      path: "/budget"
      fullPath: "/budget"
      preLoaderRoute: typeof AppBudgetRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/expenses": {
      id: "/_app/expenses"
      path: "/expenses"
      fullPath: "/expenses"
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/settings": {
      id: "/_app/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/expenses_/new": {
      id: "/_app/expenses_/new"
      path: "/expenses/new"
      fullPath: "/expenses/new"
      preLoaderRoute: typeof AppExpensesNewRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/expenses_/$expenseId/edit": {
      id: "/_app/expenses_/$expenseId/edit"
      path: "/expenses/$expenseId/edit"
      fullPath: "/expenses/$expenseId/edit"
      preLoaderRoute: typeof AppExpensesExpenseIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBudgetRoute: typeof AppBudgetRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppExpensesNewRoute: typeof AppExpensesNewRoute
  AppExpensesExpenseIdEditRoute: typeof AppExpensesExpenseIdEditRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBudgetRoute: AppBudgetRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppExpensesNewRoute: AppExpensesNewRoute,
  AppExpensesExpenseIdEditRoute: AppExpensesExpenseIdEditRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
